-- MySQL Script generated by MySQL Workbench
-- Mon 07 Mär 2016 19:48:06 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vop` ;

-- -----------------------------------------------------
-- Schema vop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `vop` ;

-- -----------------------------------------------------
-- Table `vop`.`trajecten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vop`.`trajecten` ;

CREATE TABLE IF NOT EXISTS `vop`.`trajecten` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `letter` VARCHAR(2) NULL,
  `naam` VARCHAR(100) NULL,
  `lengte` INT NULL,
  `optimale_reistijd` INT NULL,
  `is_active` TINYINT(1) NULL DEFAULT 1,
  `start_latitude` VARCHAR(45) NULL,
  `start_longitude` VARCHAR(45) NULL,
  `end_latitude` VARCHAR(45) NULL,
  `end_longitude` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vop`.`providers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vop`.`providers` ;

CREATE TABLE IF NOT EXISTS `vop`.`providers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(100) NULL,
  `is_active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vop`.`metingen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vop`.`metingen` ;

CREATE TABLE IF NOT EXISTS `vop`.`metingen` (
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reistijd` INT NULL,
  `optimal` INT NULL,
  `traject_id` INT NOT NULL,
  `provider_id` INT NOT NULL,
  INDEX `fk_Meting_Traject_idx` (`traject_id` ASC),
  INDEX `fk_Meting_Provider1_idx` (`provider_id` ASC),
  PRIMARY KEY (`traject_id`, `provider_id`, `timestamp`),
  CONSTRAINT `fk_Meting_Traject`
    FOREIGN KEY (`traject_id`)
    REFERENCES `vop`.`trajecten` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Meting_Provider1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `vop`.`providers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vop`.`waypoints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vop`.`waypoints` ;

CREATE TABLE IF NOT EXISTS `vop`.`waypoints` (
  `volgnr` INT NOT NULL,
  `traject_id` INT NOT NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  PRIMARY KEY (`volgnr`, `traject_id`),
  INDEX `fk_waypoints_1_idx` (`traject_id` ASC),
  CONSTRAINT `fk_waypoints_1`
    FOREIGN KEY (`traject_id`)
    REFERENCES `vop`.`trajecten` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
